### ISSUE TITLE
Properties cannot contain single quotes

### ISSUE THREAD

**Issue by arendjr** [m93a/filtrex#20]
This issue is similar to #11, but applies to properties escaped using single quotes instead. Because there is no support for escaping single quotes, it is not possible to refer to any properties in the input that have single quotes in them.

**Comment by m93a** [comment]
I'm aware of this issue, but I'm not sure it's important anyhow. Since the input is completely in the developer's control, they can easily escape the quotes themselves. In most cases I would even consider it a bad practice to give the user data with any non-straightforward names.

**Comment by arendjr** [comment]
The use case we have is that we allow users to write expressions that will be evaluated on arbitrary CSV files, which they can use to select subsets of those files. Because we allow arbitrary files as input, the files can have quotes as part of the column names, and the user would likely expect to find the column name with the quote in there, as that's what it looks like in there input file.

But I do agree it's a rare case and if we normalize column names in such cases

**Comment by m93a** [comment]
Hmmm… Considering the alternative for you would be something like this:
```
' is escaped by "
" is escaped by \"
\ is escaped by \\
```
I think it's quite reasonable to add single-quote escaping to core filtrex. Feel free to make a PR, and if you do, make it from the [v2.0.0 branch](https://github.com/m93a/filtrex/tree/v2.0.0), please.

**Comment by m93a** [comment]
Fixed in 67ebb42.

**Comment by arendjr** [comment]
Awesome, thanks!

**Comment by m93a** [comment]
I just noticed that the final syntax isn't mentioned anywhere. In the end I went with the standard notation: `\'` to escape single quotes, `\\` to escape backslash. I might update the README to mention this.
