### ISSUE TITLE
Fail early and reliably

### ISSUE THREAD

**Issue by m93a** [m93a/filtrex#22]
Right now, unknown symbols return `undefined`, rather than returning a descriptive error:
```javascript
compileExpression('a', {b: 4})
// undefined
compileExpression('foo of bar')({ bar: 4 })
// undefined
```
This way, expressions are prone to bugs:
```javascript
compileExpression('widht > 500', {width: 600})
// false (0)
```

There should be an API for errors. Errors should be machine-readable and easily localisable by the developer. Errors should be ~~thrown~~ returned much more often.

**Comment by lublak** [comment]
@m93a but it would be better to make it optional, since I, for example, work with this undefined.

**Comment by m93a** [comment]
> _“Every change breaks someone's workflow.”_

![XKCD Comic. Changes in version 10.17: The CPU no longer overheats when you hold down spacebar. Comments: LongitmeUser4 writes: This update broke my workflow! my control key is hard to reach, so I hold spacebar instead, and I configured Emacs to interpret a rapid temperature rise as "control". Admin writes: That's horrifying. LongtimeUser4 writes: Look, my setup works for me. Just add an option to reenable spacebar heating.](https://imgs.xkcd.com/comics/workflow.png)

That said, there **is** an [easy walkaround](https://stackblitz.com/edit/mbhn8p?file=index.ts) :)
