### ISSUE TITLE
v2.1.0 breaks with PnP

### ISSUE THREAD

**Issue by nodeworks** [m93a/filtrex#23]
Getting this message with v2.1.0 (works fine with v2.0.0) using Yarn PnP.

![Screen Shot 2020-09-16 at 7 54 29 PM](https://user-images.githubusercontent.com/5272855/93403834-9346fb80-f856-11ea-8f08-1db1cdedbfbf.png)

**Comment by feskovio** [comment]
Hi @nodeworks 
Had this issue on v2.0.0 and fixed it the following way:
const filtrex = require("filtrex/src/filtrex"); ==>const filtrex = require("filtrex/lib/filtrex");

**Comment by nodeworks** [comment]
thanks @feskovio that worked!

**Comment by m93a** [comment]
Hey @nodeworks and @feskovio,
thanks for letting me know! I'm glad you figured it out, but I'm curious: is there reason why you import `filtrex/lib/filtrex` and not just `filtrex`? I test the versions on [filtrex-react-sample](https://github.com/m93a/filtrex-react-sample) and there was no problem with the update.
