### ISSUE TITLE
Object key with dash symbol

### ISSUE THREAD

**Issue by chriszirkel** [m93a/filtrex#24]
Hi,

my JSON object contains the dash symbol (-) within the, e.g. `{ 'seller-sku': 'AB-CDEF-GH' }` and my filter expression `var expression = 'seller-sku == "AB-CDEF-GH"';` does not work with that.

So I would need to pre-parse the object and change every object key to camelCase or PascalCase. 

Would it be possible to include all possible JSON keys within the expression?

**Comment by m93a** [comment]
Hey Chris!
Sorry for my late reply. In filtrex, dash is parsed as a minus sign, the same as JavaScript. You don't have to preprocess anything, instead you can use a quoted symbols (see [filtrex syntax](https://github.com/m93a/filtrex#Expressions)). A trivial example of how to do this would be:
```typescript
let data = { 'seller-sku': 'AB-CDEF-GH' }
let expr = `'seller-sku' == "AB-CDEF-GH"`

let fn = compileExpression(expr)
fn(data) // 1
```
[Live example](https://runkit.com/embed/l6du7k4y2m9r).

Please let me know if this worked for you.
Best regards

**Comment by chriszirkel** [comment]
Hi Michal!

thank you very much for this answer. It's exactly what I was looking for. 

Best regards
Chris
