### ISSUE TITLE
Expressions to customise return value

### ISSUE THREAD

**Issue by Ali1** [m93a/filtrex#26]
Is there scope in this project to allow expressions that calculate a return value?

```
var returnExpression = 'text in response'';
let myReturn = compileReturnExpression(returnExpression);
return myReturn({response: {code: 200, text: 'hi'}}); // returns hi
```

**Comment by m93a** [comment]
Hi!
This is indeed in the scope of this project. In fact it is perfectly doable right now! You just need to change `in` to `of`. The `in` operator checks whether a value is present in an array, meanwhile the `of` operator accesses properties of objects.
Here's a working example: https://runkit.com/embed/6o7ejjvmtvri

Let me know if this fixed your issue 😁️

**Comment by Ali1** [comment]
What a neat library. While I have you, what's the best way to compare a part of the data against time with this? customprop a timestamp or date object?? Couldn't figure out what I need to do to this

```
function supplyTimestamp(){}
let options = {

};
var myfilter = compileExpression('timestamp of data > _timestamp');
myfilter({data : { timestamp: 4543623626 }});
```
Thanks!!

**Comment by m93a** [comment]
I'm not sure I understand your question. Do you want to find a user-friendly way to choose the cutoff date? Something like `timestamp of data > date("2020-21-01")`? This would be possible using a custom function:
```javascript
function date(str) { your implementation }

let options = {
   extraFunctions: { date }
};
let myfilter = compileExpression('timestamp of data > date("2020-21-01")', options);
myfilter({data : { timestamp: 4543623626 }});
```

Or you just want to pass more data to the expression? The simplest way would be to pass the data the intended way:
```javascript
function supplyTimestamp(){ your implementation }
let myfilter = compileExpression('timestamp of data > _timestamp');

myfilter({
  data : { timestamp: 4543623626 },

  _timestamp: suplyTimestamp(),

  /* or alternatively */
  get _timestamp() { return suplyTimestamp() }
});
```

If you didn't like this for some reason, custom `prop` is of course an option:
```javascript
function customProp(name, get) {
  if (name === '_timestamp') return supplyTimestamp()
  else return get(name)
}

let options = { customProp };
let myfilter = compileExpression('timestamp of data > _timestamp', options);
myfilter({data : { timestamp: 4543623626 }});
```

**Comment by Ali1** [comment]
> ```js
> function customProp(name, get) {
>   if (name === '_timestamp') return supplyTimestamp()
>   else return get(name)
> }
> 
> let options = { customProp };
> let myfilter = compileExpression('timestamp of data > _timestamp', options);
> myfilter({data : { timestamp: 4543623626 }});
> ```
Love this solution thanks.

Is there a reason why you return 1 and 0 for conditional expressions rather than a boolean? booleans would be great to better confirm that the expression entered is a conditional type of expression.

**Comment by m93a** [comment]
The decission to use only numbers and strings was made at the very beginning of filtrex to make matters as simple as they can possibly be. (Since then arrays and objects also appeared.) However, you are right that from the user's perspective, it doesn't necessarily make sense that `0` gets interpreted as “filter this thing out” and for example `-3` gets interpreted as “leave it there”. It would probably be smart to introduce booleans once I get around to make v3 of filtrex (I've opened issue #27 about it). In the meantime, you can make yourself a fork and mess around ;) If you want to turn off automatic coertion of booleans to numbers, the relevant function is [`coerceBoolean`](https://github.com/m93a/filtrex/blob/master/src/filtrex.js#L22).
