### ISSUE TITLE
client-side dist filtrex.js ?

### ISSUE THREAD

**Issue by smartsl** [m93a/filtrex#32]
Need to use it in a browser. Thank you for any advice.

**Comment by m93a** [comment]
Hey @smartsl,
Currently, you have to use a bundler like [Webpack](https://webpack.js.org/) or [Rollup](https://rollupjs.org/) in order to use filtrex in a browser. However, I agree that more options should be available – I'll see what I can do.

**Comment by m93a** [comment]
I've added a gulp script that compiles filtrex for Common JS, ES Modules and the browser. Check out [the new version](https://github.com/m93a/filtrex/releases/tag/v2.2.0) and let me know if it worked for you. You're probably interested in the `browser.min.js` file.

**Comment by smartsl** [comment]
The ```browser.min.js``` works well.
