### ISSUE TITLE
Change the ternary operator to `if..then..else`

### ISSUE THREAD

**Issue by m93a** [m93a/filtrex#34]
Many languages, including [Python](https://pythonexamples.org/python-ternary-operator/) and [CoffeeScript](https://coffeescript.org/#conditionals), use keywords `if` and `else` instead of the ternary operator `?:`. This approach is better aligned with the goals of filtrex. In particular, the CoffeeScript version (`if a then b else c`) is very close to natural language which makes it layman-friendly.

This change is scheduled as a breaking change in v3.0.0. **Any discussion is welcome.**

**Comment by m93a** [comment]
This also solves the incorrect precedence of the ternary operator that is present in filtrex v2, see [this SO post](https://stackoverflow.com/a/68061276/1137334).

**Comment by m93a** [comment]
Add back `a ? b : c` and make it deprecated.

**Comment by mikefarah** [comment]
Why not support both - personally I prefer ternary operators?
