### ISSUE TITLE
Access nested object properties

### ISSUE THREAD

**Issue by bartbutenaers** [m93a/filtrex#45]
Dear,

Thanks for sharing this very useful library!

I'm a bit confused about nested object properties.
I pass an object like this:

![image](https://user-images.githubusercontent.com/14224149/130564072-688d0c50-09d1-43e4-9fa3-b823f7368acc.png)

Which we try to validate using following expression:
```
msg.payload.open == true
```

From the readme page I understood this should be possible:

![image](https://user-images.githubusercontent.com/14224149/130563864-8a2847ae-a523-4e54-b1b5-0074aed0d5ae.png)

But I might have misinterpreted this??
And indeed while debugging, I see that this library checks whether the object has its ***own*** property "msg.payload.open" which is of course not the case:

![image](https://user-images.githubusercontent.com/14224149/130564503-64cc0eba-565e-4a51-9cb4-ecedf318b1b7.png)

Which means the nested property cannot be found :-(

However when I change the code to this:
```
    function prop(name, obj) {
        return name.split('.').reduce((obj, prop) => {
            return obj && obj[prop] ? obj[prop] : undefined;
        }, obj)
    }

    function safeGetter(obj) {
        return function get(name) {
            return name.split('.').reduce((obj, prop) => {
                return obj && obj[prop] ? obj[prop] : undefined;
            }, obj)
        }
    }
```
Then the nested property can be found without problems:
![image](https://user-images.githubusercontent.com/14224149/130564812-2404bdf1-0fc5-433b-8069-5868342b2e64.png)

Thanks !!!
Bart

**Comment by m93a** [comment]
Closing this in favor of #44. If there's anything to discuss, let's discuss it there :)
