### ISSUE TITLE
Comparing a user supplied string to a string on the data object

### ISSUE THREAD

**Issue by tzaitoun** [m93a/filtrex#58]
I'm trying to implement a way to filter out objects based on the user supplied string. I wanted to string match using a fuzzy match algorithm, but when defining a custom function:
```
fuzzy(inputString, matchString) {
   // return boolean
}
```

and setting the filter expression to this (**example data object:** `{ name: 'John K', age: 18 }`):
`fuzzy(name, 'John')`

doesn't pass 'John' to the custom function. Is there a way to do this?

**Comment by m93a** [comment]
Hey Talat!
Sorry for the late reply! The problem with your code is that you use single quotes – by looking at the [Readme](https://github.com/m93a/filtrex#expressions), you can see that strings in Filtrex use double quotes while single quotes are reserved for symbols. In your case, all four of these are identical:
  * `fuzzy(name, John)`
  * `fuzzy('name', John)`
  * `fuzzy(name, 'John')`
  * `fuzzy('name', 'John')`

What you actually want is:
```
fuzzy(name, "John")
```

**Comment by m93a** [comment]
Also: v3 has better error discoverability. If you run your original code in v3, you'll get an UnknownPropertyError, as you should:

![image](https://user-images.githubusercontent.com/1671665/167861931-bcbfe2b0-be3e-4941-8159-4b3c7f810e4e.png)

**Comment by tzaitoun** [comment]
Thank you, this was very helpful. I'll definitely check v3 out.

**Comment by m93a** [comment]
Update: I've finally published v3 as a [stable release](https://www.npmjs.com/package/filtrex/v/3.0.0). Therefore you don't have to worry about release candidates and the like :)
