### ISSUE TITLE
Jison NPM package has Node dependencies

### ISSUE THREAD

**Issue by gunzip** [m93a/filtrex#9]
It looks that the Makefile refers to some "src/jison.js" file which is not in the repository
so when you call `const Jison = require("jison").Jison;` it will reach the jison package in `node_modules` which depends on some nodejs stuff like the 'fs' module:

https://github.com/zaach/jison/blob/master/package.json#L37 (enbf-parser)
-> https://github.com/zaach/ebnf-parser/blob/master/ebnf-parser.js#L2 (ebnf-transform)
-> https://github.com/zaach/ebnf-parser/blob/master/ebnf-transform.js#L2 (transform-parser)
-> https://github.com/zaach/ebnf-parser/blob/master/transform-parser.js#L623 (fs)

that's why `import * as filtrex from "filtrex"` fails in browser runtime:

```
This dependency was not found:
⠀
* fs in ./node_modules/ebnf-parser/parser.js, ./node_modules/ebnf-parser/transform-parser.js and 2 others

To install it, you can run: npm install --save fs

```

is there any way to use the npm package in the browser ?

**Comment by m93a** [comment]
You're right, the NPM Jison package is very far from ideal. Have you tried actually installing `fs` to see if the bundled version actually works in browser? Because it should. However, I'm not closing this issue because it's something we should fix.

**Comment by m93a** [comment]
What bundler do you use? There are solutions to include a dummy `fs` in webpack, for example, which you can try as a walkaround.

I chose NPM over a bundled `jison.js` because I thought it might give us some updates, but since Jison seems to be long dead, I'll just go back to including the file. But don't have time rn, so if you do, feel free to make a PR.

**Comment by m93a** [comment]
@gunzip Can you try the npm package `@m93a/filtrex^2.1.0-beta1`? It should have no dependency at all, but I haven't tested it outside Node yet.

**Comment by m93a** [comment]
Tested in [m93a/filtrex-react-sample](https://github.com/m93a/filtrex-react-sample), everything seems to work all right.
